version: "3.8"

services:

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  app:
    build: .
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    command: ['./wait-for-it.sh', 'postgres:5432', '--',
              'python', 'manage.py', 'runserver', '0.0.0.0:8000']

  postgres:
    image: postgres:15
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    command: ["-c", "max_locks_per_transaction=128"]
