name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt -r requirements.dev.txt

      - name: Lint with black
        run: |
          . venv/bin/activate
          black --check --verbose .

      - name: Lint with pylint
        run: |
          . venv/bin/activate
          pylint **/*.py

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt -r requirements.dev.txt

      - name: Run tests
        env:
          DATABASE_URL:
            sqlite://:memory:
        run: |
          . venv/bin/activate
          pytest --nomigrations --reuse-db
